### ISSUE TITLE
Response from RAML Spec

### ISSUE THREAD

**Issue by alleypa** [dmitrisweb/raml-mocker-server#3]
Ideally we should make it configurable what to return from request. Either the example json or the schema implementing faker.js

**Comment by dmitrisweb** [comment]
@alleypa, new preference added: prioritizeBy, which could be set to 'example' or 'schema'.
In the future I might add another option 'order' - which will depend on the order in the RAML file, but apparently this is not that easy to do.

Please update version to the latest (0.1.4)

**Comment by alleypa** [comment]
thanks @dmitrisweb the sample json is returned as expected
