### ISSUE TITLE
raml mocker server update

### ISSUE THREAD

**Issue by alleypa** [dmitrisweb/raml-mocker-server#9]
@dmitrisweb, @dmitryshimkin,

The raml-mocker as had update to its dependencies. i.e. fakerJS 3.1.0 etc. Current version of raml-mocker is 0.2.0. Can we have the raml-mocker-server updated to track version 0.2.0 of the raml-mocker. Because currently Raml-mocker-server is broken because of the old version of Raml-Mocker.

Thx

**Comment by dmitrisweb** [comment]
Dear Olu,
"raml-mocker": "^0.1.14" will resolve all minor versions 0.x.x, so this is not an issue

**Comment by dmitryshimkin** [comment]
@dmitrisweb Actually before version `1.0.0` the caret means "get the latest _patch_ for the given minor version". Thus `^0.1.14` equals to `>=0.1.14 <0.2.0`. And after version `1.0.0` the caret works differently — "get the latest minor and patch for the given major version". 

But anyway currently `raml-mocker` is defined as `^0.2.0` that points to the latest available version :-)

**Comment by alleypa** [comment]
thanks @dmitrisweb
